{% set name = "py3-validate-email" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d043f6af4bc31b117d1d30bbfc5a5f6b293ec32acd6bc5d21ca42dd86c145d60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dnspython ~=2.2
    - filelock ~=3.7
    - idna ~=3.3
    - python >=3.6
    - typing-extensions ~=4.4

test:
  imports:
    - validate_email
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://gitea.ksol.io/karolyi/py3-validate-email
  summary: Email validator with regex, blacklisted domains and SMTP checking.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
