{% set name = "py3-validate-email" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ksol.io/karolyi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 16ffe0e09fdb0ed798d345eea50381a1d3599e3f2e929178ce11c6cf3153d15d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dnspython ~=2.2
    - filelock ~=3.7
    - idna ~=3.3
    - python >={{ python_min }}
    - typing-extensions ~=4.4

test:
  imports:
    - validate_email
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://gitea.ksol.io/karolyi/py3-validate-email
  summary: Email validator with regex, blacklisted domains and SMTP checking.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
